# Taller 04: Manejo de Python
## Métodos Numéricos

Brevemente repasaremos de matrices en Numpy y los métodos matriciales



## Algunas consideraciones en NUMPY
Verifiquemos el uso de matrices en python antes de comenzar

In [1]:
# Importamos la libreria numpy, y los elementos que necesitamos
import numpy as np
import numpy.linalg as la

In [2]:
# Definición de un vector
vector = np.array([1, 2, 3])

# Trasposición y transpuesta de un vector
vector.T

array([1, 2, 3])

In [3]:
# Definición de matrices
matriz = np.array([[1, 2, 3], [2, 3, 5], [9, 10, 2]])

# Matrices y traspuesta de una matriz
matriz.T, matriz

(array([[ 1,  2,  9],
        [ 2,  3, 10],
        [ 3,  5,  2]]),
 array([[ 1,  2,  3],
        [ 2,  3,  5],
        [ 9, 10,  2]]))

In [4]:
# Multiplicación matricial entre matrices y vectores
matriz @ vector

array([14, 23, 35])

In [5]:
# Normas en Numpy
la.norm(vector, -np.inf)

1.0

In [6]:
# Valores propios de una matriz
la.eig(matriz)

(array([11.96774691, -0.24836323, -5.71938368]),
 array([[-0.31226591, -0.71672364, -0.25539911],
        [-0.51480202,  0.67990711, -0.43620265],
        [-0.79841648, -0.15502759,  0.86284329]]))

In [7]:
# Definición de las submatrices de un sistema: Diagonal
np.diag(matriz)

array([1, 3, 2])

In [8]:
# Definición de las submatrices de un sistema: triangular superior
np.triu(matriz, 1)

array([[0, 2, 3],
       [0, 0, 5],
       [0, 0, 0]])

## Método de Jacobi
Definamos el método y comparemos los resultados con los obtenidos en MATLAB

In [9]:
def jacobi(A, b, X0, delta, maxI):

    # Entrada  - A es una matriz no singular  N x N
    #          - B es una matriz  N x 1
    #          - P es una matriz  N x 1; los supuestos iniciales
    #	       - delta es la tolerancia para  P
    #	       - max1 es el numero maximo de iteraciones
    # Salida   - X es una matriz  N x 1: la aproximacion de jacobi a
    #	         la solucion de  AX = B

    #  METODOS NUMERICOS: Programas en Matlab
    # (c) 2004 por John H. Mathews y Kurtis D. Fink
    #  Software complementario acompañando al texto:
    #  METODOS NUMERICOS con Matlab, Cuarta Edicion
    #  ISBN: 0-13-065248-2
    #  Prentice-Hall Pub. Inc.
    #  One Lake Street
    #  Upper Saddle River, NJ 07458

    D = np.diag(np.diag(A))
    L = -np.tril(A, -1)
    U = -np.triu(A, 1)

    TJ = la.inv(D) @ (L + U)
    CJ = la.inv(D) @ b

    for k in range(1, maxI +1):

        X = TJ @ X0 + CJ

        err = abs(la.norm(X - X0))
        rerr = err / (la.norm(X) + delta)

        X0 = X

        if err < delta or rerr < delta: break


    return X, err, rerr, k

In [10]:
# Definamos las variables del sistema
A = np.array([[3, 1, -1], [-1, 4, 1], [-1, 2, 5]])      # Matriz de coeficientes de sistema
b = np.array([-1, 3, 2])                                # Vector de valores independientes del sistema
X0 = np.array([1, -1, -1])                              # Aproximación inicial

X, err, rerr, k = jacobi(A, b, X0, 1e-15, 1000)         # Aplicación del método

print(f"Se requierieron {k} iteraciones y se obtuvo un error de: {rerr : 2}")

Se requierieron 37 iteraciones y se obtuvo un error de:  4.444211564840654e-16


In [11]:
%timeit jacobi(A, b, X0, 1e-15, 1000)       # Tiempos de ejecución del método

607 µs ± 37.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
residual = A @ X - b        # Residual de la aproximación
la.norm(residual)           # Norma euclideana del residual

6.661338147750939e-16

## Actividad: Haz tu propio código
Completa el código asociado al método de SOR, y verifica los resultados que obtuvimos en matlab tomando omega como 1, que es el caso en que SOR es equivalente al método Gauss-Seidel

In [13]:
def sor(A, b, X0, w, delta, maxI):

    # Entrada  - A es una matriz no singular  N x N
    #          - B es una matriz  N x 1
    #          - P es una matriz  N x 1; el supuesto inicial
    #          - w parametro de sobrerelajacion (0<w<2)
    #	       - delta es la tolerancia para  P
    #	       - max1 es el numero maximo de iteraciones
    # Salida   - Y es una matriz  N x 1: la aproximacion de SOR a
    #	         la solucion de  AX = B

    #  METODOS NUMERICOS: Programas en Matlab
    # (c) 2004 por John H. Mathews y Kurtis D. Fink
    #  Software complementario acompañando al texto:
    #  METODOS NUMERICOS con Matlab, Cuarta Edicion
    #  ISBN: 0-13-065248-2
    #  Prentice-Hall Pub. Inc.
    #  One Lake Street
    #  Upper Saddle River, NJ 07458

    D = np.diag(np.diag(A))
    L = -np.tril(A, -1)
    U = -np.triu(A, 1)

    # --- Tú código aquí! --- #

    for k in range(1, maxI +1):

        # --- Tú código aquí! --- #

        err = abs(la.norm(X - X0))
        rerr = err / (la.norm(X) + delta)

        X0 = X

        if err < delta or rerr < delta: break


    return X, err, rerr, k