# Taller 03: Manejo de Python
## Métodos Numéricos

Brevemente repasaremos los conceptos de Newton y Newton modificado



In [38]:
# Importamos la libreria numpy, y los elementos que necesitamos
import numpy as np
import numpy.linalg as la

In [14]:
vector = np.array([1, 2, 3])

vector.T

array([1, 2, 3])

In [16]:
matriz = np.array([[1, 2, 3], [2, 3, 5], [9, 10, 2]])

matriz.T, matriz

(array([[ 1,  2,  9],
        [ 2,  3, 10],
        [ 3,  5,  2]]),
 array([[ 1,  2,  3],
        [ 2,  3,  5],
        [ 9, 10,  2]]))

In [19]:
matriz @ vector

array([14, 23, 35])

In [39]:
la.norm(vector, -np.inf)

1.0

In [40]:
la.eig(matriz)

(array([11.96774691, -0.24836323, -5.71938368]),
 array([[-0.31226591, -0.71672364, -0.25539911],
        [-0.51480202,  0.67990711, -0.43620265],
        [-0.79841648, -0.15502759,  0.86284329]]))

In [42]:
np.diag(matriz)

array([1, 3, 2])

In [44]:
np.triu(matriz, 1)

array([[0, 2, 3],
       [0, 0, 5],
       [0, 0, 0]])

In [61]:
def jacobi(A, b, X0, delta, maxI):

    # Entrada  - A es una matriz no singular  N x N
    #          - B es una matriz  N x 1
    #          - P es una matriz  N x 1; los supuestos iniciales
    #	       - delta es la tolerancia para  P
    #	       - max1 es el numero maximo de iteraciones
    # Salida   - X es una matriz  N x 1: la aproximacion de jacobi a
    #	         la solucion de  AX = B

    #  METODOS NUMERICOS: Programas en Matlab
    # (c) 2004 por John H. Mathews y Kurtis D. Fink
    #  Software complementario acompañando al texto:
    #  METODOS NUMERICOS con Matlab, Cuarta Edicion
    #  ISBN: 0-13-065248-2
    #  Prentice-Hall Pub. Inc.
    #  One Lake Street
    #  Upper Saddle River, NJ 07458

    D = np.diag(np.diag(A))
    L = -np.tril(A, -1)
    U = -np.triu(A, 1)

    TJ = la.inv(D) @ (L + U)
    CJ = la.inv(D) @ b

    for k in range(1, maxI +1):

        X = TJ @ X0 + CJ

        err = abs(la.norm(X - X0))
        rerr = err / (la.norm(X) + delta)

        X0 = X

        if err < delta or rerr < delta: break


    return X, err, rerr, k

In [63]:
A = np.array([[3, 1, -1], [-1, 4, 1], [-1, 2, 5]])
b = np.array([-1, 3, 2])
X0 = np.array([1, -1, -1])

X, err, rerr, k = jacobi(A, b, X0, 1e-15, 1000)

print(f"Se requierieron {k} iteraciones y se obtuvo un error de: {rerr : 2}")

Se requierieron 37 iteraciones y se obtuvo un error de:  4.44421156484066e-16


In [56]:
%timeit jacobi(A, b, X0, 1e-15, 1000)

646 µs ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
