# Taller 02: Manejo de Python
## Métodos Numéricos

Brevemente repasaremos los conceptos de Newton y Newton modificado



In [41]:
# Importamos la libreria numpy, y los elementos que necesitamos
from numpy import sin, cos

## Newton y extensiones
Brevemente crearemos el método de Newton, y verificaremos su funcionamiento.
- **Pendiente:** Método para Newton Modificado.

In [9]:
# Creamos el método de Newton
def newton(f, df, p0, delta, epsilon, max1):

    """
    Entrada - f funcion creada con @
            - df funcion derivada creada con @
            - p0 es la aproximacion inicial a cero de  f
            - delta es la tolerancia para  p0
            - epsilon es la tolerancia para los valores de la funcion  y
            - max1 es el numero maximo de iteraciones
    Salida  - p0 es la aproximacion de Newton-Raphson hacia cero
            - err es el error estimado para  p0
            - k es el numero de iteraciones
            - y es el valor de la funcion  f(p0)
    """

    for k in range(1, max1 +1):

        p1 = p0 - f(p0) / df(p0)

        err = abs(p1 - p0)
        relerr = 2 * err /(abs(p1) + delta)

        p0 = p1
        y = f(p0)

        if (err < delta) or (relerr < delta) or (abs(y) < epsilon):
            break

    return p0, err, k, y

In [39]:
# Declaramos la función y su derivada respecitivamente
f = lambda x : x**2 - 4 * x * sin(x) + (2 * sin(x))**2
df = lambda x : 2 * x - 4 * x*cos(x) - 4*sin(x) + 8 * sin(x)*cos(x)

# Llamamos al método de newton, y comparamos con MATLAB
p0, err, k, y = newton(f, df, 1.5, 1e-15, 1e-15, 100)

# Imprimimos resultados
print(f"La aproximación es: {p0}, y tomamos {k} iteraciones, con error {err}")

La aproximación es: 1.895494258862328, y tomamos 24 iteraciones, con error 1.4561147843039635e-08


- Verifiquemos el rendimiento entre el software MATLAB y el lenguaje Python.

In [40]:
%timeit newton(f, df, 1.5, 1e-15, 1e-15, 100)

215 µs ± 3.92 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Veamos que en MATLAB la ejecución del método toma alrededor de 0.03 seg, en cambio python para la ejecución del código escrito anteriormente toma 215useg, una diferencia amplia de rendiemiento

## Matrices y uso de numpy
Veamos los comandos básicos de numpy, y los usos que podemos emplear para el curso

In [43]:
#Importamos numpy
import numpy as np

In [92]:
# Definamos una lista, y verifiquemos que NO es un vector
x = [1, 2, 3]
print(x * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [94]:
# Los vectores toman forma de Arrays
x = np.array([1, 2, 3])

print(x + 1)

[2 3 4]


In [95]:
# Y naturalmente las matrices toman forma de vectores de vectores
x = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
y = 3 * np.ones(x.shape)
print(x + y)

[[ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [97]:
# La multiplicación matricial toma formas distintas
print(x * y)    # Multiplicación de elementos

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


In [98]:
print(x @ y)    # Multiplicación matricial

[[18. 18. 18.]
 [45. 45. 45.]
 [72. 72. 72.]]


- Veamos algunos métodos que toman los arrays

In [102]:
# Matrices comunes:
np.ones((3, 3))     # Matriz de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.zeros((3, 3))    # Matriz de ceros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
np.eye(3)           # Matriz Identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
# Métodos básicos de matrices
x.shape     # Forma de la matriz (Fila, Columna)         

(3, 3)

In [106]:
x[:, 1]     # Slicing de regiones de la matriz

array([2, 5, 8])